# Generated by Django 2.2.3 on 2019-08-06 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='kane@99.com', max_length=254)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='practice.user')),
            ],
        ),
    ]
