# Generated by Django 2.2.3 on 2019-08-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='practice.user'),
        ),
        migrations.CreateModel(
            name='step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('receipt', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='practice.receipt')),
            ],
            options={
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('receipt', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='practice.receipt')),
            ],
            options={
                'ordering': ('text',),
            },
        ),
    ]
